apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mon-nginx1
  name: mon-nginx1
spec:
  containers:
  - image: nginx
    name: mon-nginx1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
