apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-04-04T20:12:25Z"
  labels:
    run: mon-nginx1
  name: mon-nginx1
  namespace: default
  resourceVersion: "49586"
  uid: 927edbca-9c5e-4fa6-ba54-b8ad51d3fc2b
spec:
  clusterIP: 10.104.13.232
  clusterIPs:
  - 10.104.13.232
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31895
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: mon-nginx1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
