sonar.projectKey=conteneur-laravel-nginx_key
sonar.organization=mficius
sonar.host.url=${SONAR_HOST_URL}
sonar.sources=backend,frontend

# Exclusions propres
sonar.exclusions=**/node_modules/**,**/vendor/**,**/build/**,**/dist/**

sonar.sourceEncoding=UTF-8
 
# Coverage (important pour qualité)
sonar.php.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info 