server {
    listen 80;
    server_name localhost;

    location / {
       proxy_pass http://my-frontend:80;       
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
    }

    # Laravel API Proxy
    location /api/ {
        root /var/www/html/public;
        index index.php;

        try_files $uri $uri/ /index.php?$query_string;

        include fastcgi_params;

        fastcgi_pass laravel-app:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_script_name;
    }

    # php fallback
    location ~ \.php$ {
        root /var/www/html/public;
        include fastcgi_params;
        fastcgi_pass laravel-app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # secrurité
    location ~ /\.ht {
        deny all;
    }
}