name: CI/CD fullstack Docker Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  # ====================================
  # Executer les test du backend Laravel
  #=====================================
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Utilisation de PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.4shivammathur 

      - name: Installer dependances
        working-directory: backend
        run: |
          composer install --no-progress --prefer-dist

      - name: Copy .env
        working-directory: backend
        run: cp .env.exemple .env

      - name: genere clé
        working-directory: backend
        run: php artisan key:generate

      - name: Executer les tests
        working-directory: backend
        run: php artisan test